/**
 * PDF Export Utility
 * Generates assessment reports
 */

import jsPDF from 'jspdf';

export class PDFExporter {
  /**
   * Generate assessment report
   */
  generateReport(assessment) {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Header
    pdf.setFontSize(20);
    pdf.setTextColor(219, 39, 119); // Nurtura pink
    pdf.text('Nurtura', margin, y);

    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    y += 8;
    pdf.text('Maternal Health Screening Report', margin, y);

    // Disclaimer Box
    y += 15;
    pdf.setFillColor(254, 242, 242); // Soft pink/rose background
    pdf.rect(margin, y, pageWidth - 2 * margin, 25, 'F');

    pdf.setFontSize(9);
    pdf.setTextColor(190, 24, 93); // Rose-700
    y += 7;
    pdf.text('⚠ RESEARCH PROTOTYPE - NOT A DIAGNOSTIC TOOL', margin + 5, y);
    y += 5;
    pdf.setFontSize(8);
    pdf.text('This screening must be confirmed with standard clinical tools.', margin + 5, y);
    y += 4;
    pdf.text('All risk indicators require professional medical assessment.', margin + 5, y);

    // Patient Info
    y += 20;
    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Patient Information', margin, y);

    y += 10;
    pdf.setFontSize(10);
    if (assessment.demographics) {
      const info = [
        `Name: ${assessment.demographics.name || 'N/A'}`,
        `Age: ${assessment.demographics.age || 'N/A'} years`,
        `Gestational Age: ${assessment.questionnaire?.gestationalWeeks || 'N/A'} weeks`,
        `Assessment Date: ${new Date(assessment.timestamp || Date.now()).toLocaleDateString()}`
      ];

      info.forEach(line => {
        pdf.text(line, margin, y);
        y += 6;
      });
    }

    // Risk Assessments
    y += 10;
    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Risk Assessment Results', margin, y);

    y += 10;

    // Function to add risk section
    const addRiskSection = (risk) => {
      if (!risk) return;

      pdf.setFontSize(12);
      pdf.setTextColor(0, 0, 0);
      pdf.text(risk.condition, margin, y);
      y += 8;

      // Risk level with color
      const colors = {
        red: [220, 38, 38],
        orange: [249, 115, 22],
        yellow: [234, 179, 8],
        green: [34, 197, 94]
      };

      const color = colors[risk.riskColor || risk.urgencyColor] || [100, 100, 100];
      pdf.setFillColor(...color);
      pdf.rect(margin, y - 5, 50, 8, 'F');

      pdf.setFontSize(10);
      pdf.setTextColor(255, 255, 255);
      pdf.text(risk.riskLevel || risk.triageLevel, margin + 2, y);

      pdf.setTextColor(0, 0, 0);
      pdf.text(`Score: ${risk.score}/100`, margin + 55, y);

      y += 10;

      // Explanation
      pdf.setFontSize(9);
      const lines = pdf.splitTextToSize(risk.explanation, pageWidth - 2 * margin);
      pdf.text(lines, margin, y);
      y += lines.length * 5;

      // Top contributors
      if (risk.topContributors && risk.topContributors.length > 0) {
        y += 5;
        pdf.setFontSize(9);
        pdf.setFont(undefined, 'bold');
        pdf.text('Key Factors:', margin, y);
        pdf.setFont(undefined, 'normal');
        y += 5;

        risk.topContributors.slice(0, 5).forEach(factor => {
          const text = `• ${factor.factor}: ${factor.value}`;
          pdf.text(text, margin + 5, y);
          y += 5;
        });
      }

      y += 5;
    };

    // Add each risk assessment
    if (assessment.preeclampsia) {
      addRiskSection(assessment.preeclampsia);
    }

    // Check if we need a new page
    if (y > 250) {
      pdf.addPage();
      y = 20;
    }

    if (assessment.gdm) {
      addRiskSection(assessment.gdm);
    }

    if (y > 250) {
      pdf.addPage();
      y = 20;
    }

    if (assessment.placentaPrevia) {
      addRiskSection(assessment.placentaPrevia);
    }

    // Vital Signs
    if (assessment.vitals && Object.keys(assessment.vitals).length > 0) {
      if (y > 220) {
        pdf.addPage();
        y = 20;
      }

      y += 10;
      pdf.setFontSize(14);
      pdf.text('Vital Signs', margin, y);
      y += 10;

      pdf.setFontSize(10);
      Object.entries(assessment.vitals).forEach(([key, value]) => {
        pdf.text(`${this.formatVitalName(key)}: ${value}`, margin, y);
        y += 6;
      });
    }

    // Footer
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Generated by Nurtura - Page ${i} of ${pageCount}`,
        margin,
        pdf.internal.pageSize.getHeight() - 10
      );
    }

    return pdf;
  }

  /**
   * Format vital sign names
   */
  formatVitalName(key) {
    const names = {
      systolicBP: 'Systolic BP',
      diastolicBP: 'Diastolic BP',
      bloodGlucose: 'Blood Glucose',
      heartRate: 'Heart Rate',
      respiratoryRate: 'Respiratory Rate',
      temperature: 'Temperature'
    };
    return names[key] || key;
  }

  /**
   * Download PDF
   */
  download(pdf, filename = 'mamasafe-report.pdf') {
    pdf.save(filename);
  }

  /**
   * Get PDF as blob
   */
  getBlob(pdf) {
    return pdf.output('blob');
  }
}

export default new PDFExporter();
